In [ ]:
from google.colab import files

uploaded = files.upload()

Saving hm.csv to hm (1).csv

In [ ]:
import pandas as pd

df=pd.read_csv('hm.csv')

df.head(10)
df_original=df.copy()

## APRIORI ALGORITHM

In [ ]:


#for val in df['Order ID']:
#  if val not in order.keys():
#    index= df['Order ID'].tolist().index(val)

#    order[val]=
#  print(val)



#for val in df['Sub-Category']:
#  index= df['Order ID'].tolist().index(val)



df1=df.groupby('Order ID')['Sub-Category'].apply(list).reset_index(name='value')
df1

          Order ID                                             value
0   CA-2019-101007                                           [Belts]
1   CA-2019-102281  [Flip flops, Bags, Formals, Flip flops, Jackets]
2   CA-2019-103730        [Sneakers, Dresses, Tops, T-shirts , Bags]
3   CA-2019-104269                                     [Sport shoes]
4   CA-2019-105018                                         [Dresses]
..             ...                                               ...
61  US-2019-152030                                     [Sport shoes]
62  US-2019-152366                                           [Jeans]
63  US-2019-156216                                         [Dresses]
64  US-2019-156867                        [Belts, Sneakers, Dresses]
65  US-2019-164147                        [Bags, Formals, Nightwear]

[66 rows x 2 columns]

In [ ]:
list_ca=[]
list_ca.extend([x for x in df1['value']])
list_ca

[['Belts'],
 ['Flip flops', 'Bags', 'Formals', 'Flip flops', 'Jackets'],
 ['Sneakers', 'Dresses', 'Tops', 'T-shirts ', 'Bags'],
 ['Sport shoes'],
 ['Dresses'],
 ['Formals'],
 ['Jackets', 'T-shirts ', 'Formals'],
 ['Tops'],
 ['Bags'],
 ['Sneakers'],
 ['Sneakers'],
 ['Heels & Flats'],
 ['Tops'],
 ['Dresses'],
 ['Socks', 'Bags'],
 ['Bags', 'Bags', 'Sport shoes', 'Dresses'],
 ['Nightwear', 'T-shirts ', 'Formals', 'T-shirts '],
 ['Jackets'],
 ['Formals', 'Formals', 'Sport shoes'],
 ['Belts', 'Bags', 'Jackets'],
 ['Belts'],
 ['Belts'],
 ['Formals', 'Formals', 'Tops'],
 ['Sneakers'],
 ['Jackets', 'Dresses'],
 ['Belts'],
 ['Formals'],
 ['Tops', 'Bags'],
 ['T-shirts '],
 ['Sport shoes', 'Tops', 'Formals', 'Jeans', 'Formals'],
 ['Heels & Flats', 'Jeans'],
 ['Tops', 'Bags', 'Dresses', 'Nightwear', 'Tops'],
 ['Jackets'],
 ['Jackets', 'Sunglasses', 'Tops', 'Sport shoes', 'Jackets', 'Jeans', 'Bags'],
 ['Jackets', 'Jackets'],
 ['Formals',
  'Formals',
  'Jackets',
  'Nightwear',
  'Dresses',
  'Sportswear',
  'Sneakers'],
 ['Socks', 'Flip flops', 'Bags', 'Sunglasses', 'Belts'],
 ['Sneakers'],
 ['T-shirts '],
 ['Sport shoes'],
 ['Jeans'],
 ['Tops', 'Formals'],
 ['Formals',
  'Sneakers',
  'Sneakers',
  'Bags',
  'Heels & Flats',
  'Sneakers',
  'Jackets'],
 ['Bags', 'Bags', 'Belts'],
 ['Belts', 'Dresses'],
 ['Jeans', 'Bags'],
 ['Formals'],
 ['Formals'],
 ['Jackets', 'Heels & Flats', 'Tops'],
 ['Tops', 'Belts'],
 ['Nightwear', 'Formals', 'Dresses', 'Sneakers', 'Sunglasses', 'Jackets'],
 ['Jeans', 'Socks'],
 ['Heels & Flats', 'Heels & Flats', 'Dresses', 'Sneakers', 'Belts'],
 ['Sport shoes', 'Sportswear'],
 ['Dresses', 'Tops'],
 ['Jeans'],
 ['Dresses', 'Formals'],
 ['Sport shoes', 'Sneakers'],
 ['Heels & Flats'],
 ['Dresses'],
 ['Sport shoes', 'Sport shoes'],
 ['Sport shoes'],
 ['Jeans'],
 ['Dresses'],
 ['Belts', 'Sneakers', 'Dresses'],
 ['Bags', 'Formals', 'Nightwear']]

In [ ]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.7/dist-packages (1.1.2)

In [ ]:
from apyori import apriori

#apriori:
association_rules=apriori(list_ca, min_support=0.006, min_confidence=0.3, min_lift=8, min_length=3)
association_results=list(association_rules)

print(type(association_results[0]))
len(association_results), association_results[0]

<class 'apyori.RelationRecord'>

(120,
 RelationRecord(items=frozenset({'Socks', 'Flip flops'}), support=0.015151515151515152, ordered_statistics=[OrderedStatistic(items_base=frozenset({'Flip flops'}), items_add=frozenset({'Socks'}), confidence=0.5, lift=11.0), OrderedStatistic(items_base=frozenset({'Socks'}), items_add=frozenset({'Flip flops'}), confidence=0.3333333333333333, lift=10.999999999999998)]))

In [ ]:
for item in association_results:
  print(type(item))
  #first index of inner list
  #contains base item and  add item
  pair=item[0]
  print(type(item[1]))
  items=[x for x in pair]
  print(type(items))
  print("Rule"+items[0]+"->"+items[1])

  #second  index of inner list
  print("Support: " +str(item[1]))

  #third index  of list located at 0th
  #of 3rd index of inner list

  print("confidence: "+ str(item[2][0][2]))
  print("lift:" +str(item[2][0][3]))
  print("==================================")

<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSocks->Flip flops
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Flip flops
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Flip flops
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Flip flops
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Flip flops
Support: 0.015151515151515152
confidence: 0.5
lift:8.25
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Socks
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Socks
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBelts->Socks
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBelts->Sunglasses
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBelts->Socks
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.030303030303030304
confidence: 0.4
lift:8.8
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.030303030303030304
confidence: 0.4
lift:8.8
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.015151515151515152
confidence: 1.0
lift:13.2
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Socks
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Nightwear
Support: 0.030303030303030304
confidence: 0.4
lift:8.8
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:8.25
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Nightwear
Support: 0.015151515151515152
confidence: 1.0
lift:13.2
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSport shoes->Jackets
Support: 0.015151515151515152
confidence: 1.0
lift:8.25
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleNightwear->Sneakers
Support: 0.030303030303030304
confidence: 0.4
lift:8.8
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSportswear->Nightwear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleNightwear->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSportswear->Sneakers
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSport shoes->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Sport shoes
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleTops->Sport shoes
Support: 0.030303030303030304
confidence: 1.0
lift:8.25
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Tops
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSportswear->Nightwear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Nightwear
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSneakers->Tops
Support: 0.015151515151515152
confidence: 1.0
lift:13.2
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Sport shoes
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Socks
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Socks
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Nightwear
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Dresses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Jackets
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sneakers
Support: 0.015151515151515152
confidence: 1.0
lift:22.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sport shoes
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Tops
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sport shoes
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Tops
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sneakers
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBags->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBelts->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleBelts->Sunglasses
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.030303030303030304
confidence: 0.4
lift:13.200000000000001
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sneakers
Support: 0.030303030303030304
confidence: 0.6666666666666666
lift:14.666666666666666
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.030303030303030304
confidence: 0.4
lift:13.200000000000001
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.030303030303030304
confidence: 0.4
lift:13.200000000000001
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Nightwear
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sneakers
Support: 0.015151515151515152
confidence: 1.0
lift:66.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sneakers
Support: 0.015151515151515152
confidence: 1.0
lift:22.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Nightwear
Support: 0.030303030303030304
confidence: 0.4
lift:8.8
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Nightwear
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:11.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Tops
Support: 0.015151515151515152
confidence: 1.0
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sportswear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSport shoes->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSport shoes->Tops
Support: 0.015151515151515152
confidence: 1.0
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleTops->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSportswear->Nightwear
Support: 0.015151515151515152
confidence: 0.5
lift:16.5
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Nightwear
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSport shoes->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleTops->Sunglasses
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:10.999999999999998
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFlip flops->Belts
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleDresses->Sneakers
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleJackets->Tops
Support: 0.015151515151515152
confidence: 0.5
lift:33.0
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Jackets
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleSunglasses->Tops
Support: 0.015151515151515152
confidence: 0.3333333333333333
lift:21.999999999999996
==================================
<class 'apyori.RelationRecord'>
<class 'float'>
<class 'list'>
RuleFormals->Nightwear

In [ ]:
cart=input(str(("Choose among the following: ",df['Sub-Category'].unique()))+" ")

#cart= 'Flip flops'

suggested=[]


support=association_results[0][1]
confidence=association_results[0][2][0][2]

for item in association_results:
  pair=item[0]
  #print(type(item[1]))
  items=[x for x in pair]
  
  if cart ==str(items[0])  :
    #print("**********item found!**********")
    #print(items[0], items[1])
    print("Suggested Items are: ", items[1])
    suggested.append(items[1])


  if cart ==str(items[1]):
    print("Suggested items are: ", items[0])
    suggested.append(items[0])
#association_results[0][0]


print("Suggested max: ",max(suggested, key=suggested.count))

('Choose among the following: ', array(['Belts', 'Dresses', 'Formals', 'Sneakers', 'Bags', 'Jackets',
       'Nightwear', 'T-shirts ', 'Heels & Flats', 'Tops', 'Sport shoes',
       'Sportswear', 'Jeans', 'Socks', 'Sunglasses', 'Flip flops'],
      dtype=object)) Socks
Suggested Items are:  Flip flops
Suggested items are:  Bags
Suggested items are:  Bags
Suggested items are:  Belts
Suggested items are:  Belts
Suggested items are:  Sunglasses
Suggested items are:  Bags
Suggested items are:  Bags
Suggested max:  Bags

In [ ]:
cart=input(str(("Choose among the following: ",df['Sub-Category'].unique()))+" ")

#cart= 'Flip flops'

suggested=[]
dict1={}

support=association_results[0][1]
confidence=association_results[0][2][0][2]

for item in association_results:
  pair=item[0]
  #print(type(item[1]))
  items=[x for x in pair]
  
  if cart ==str(items[0])  :
    #print("**********item found!**********")
    #print(items[0], items[1])
    print("Suggested Items are: ", items[1])
    suggested.append(items[1])

    dict1[items[1]]=(item[2][0][2])
    print((item[2][0][2]))


  if cart ==str(items[1]):
    print("Suggested items are: ", items[0])
    print((item[2][0][2]))
    suggested.append(items[0])
    dict1[items[0]]=(item[2][0][2])
#association_results[0][0]


def get_key(val, my_dict):
    for key, value in my_dict.items():
         if val == value:
             return key



#print("Max Suggested:", str(get_key(max(dict1.values(), dict1))))

('Choose among the following: ', array(['Belts', 'Dresses', 'Formals', 'Sneakers', 'Bags', 'Jackets',
       'Nightwear', 'T-shirts ', 'Heels & Flats', 'Tops', 'Sport shoes',
       'Sportswear', 'Jeans', 'Socks', 'Sunglasses', 'Flip flops'],
      dtype=object)) Socks
Suggested Items are:  Flip flops
0.5
Suggested items are:  Bags
0.5
Suggested items are:  Bags
0.3333333333333333
Suggested items are:  Belts
0.5
Suggested items are:  Belts
0.3333333333333333
Suggested items are:  Sunglasses
0.5
Suggested items are:  Bags
0.5
Suggested items are:  Bags
0.3333333333333333

In [ ]:
print("Max suggested: {} with Confidence: {}".format(max(zip(dict1.values(), dict1.keys()))[1], max(zip(dict1.values(), dict1.keys()))[0]))

Max suggested: Sunglasses with Confidence: 0.5

## COLLABORATIVE FILTERING USING KNN

In [ ]:
#!pip install scikit-surprise

In [ ]:
# load_data.py

#import pandas as pd
#from surprise import Dataset
#from surprise import Reader

# This is the same data that was plotted for similarity earlier
# with one new user "E" who has rated only movie 1
#ratings_dict = {
#    "item": [1, 2, 1, 2, 1, 2, 1, 2, 1],
#    "user": ['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E'],
#    "rating": [1, 2, 2, 4, 2.5, 4, 4.5, 5, 3],
#}

#df = pd.DataFrame(ratings_dict)
#reader = Reader(rating_scale=(1, 5))

# Loads Pandas dataframe
#data = Dataset.load_from_df(df[["user", "item", "rating"]], reader)
# Loads the builtin Movielens-100k data
#movielens = Dataset.load_builtin('ml-100k')

In [ ]:
'''# recommender.py

from surprise import KNNWithMeans

# To use item-based cosine similarity
sim_options = {
    "name": "cosine",
    "user_based": False,  # Compute  similarities between items
}
algo = KNNWithMeans(sim_options=sim_options)'''

'# recommender.py\n\nfrom surprise import KNNWithMeans\n\n# To use item-based cosine similarity\nsim_options = {\n    "name": "cosine",\n    "user_based": False,  # Compute  similarities between items\n}\nalgo = KNNWithMeans(sim_options=sim_options)'

In [ ]:
#data

In [ ]:
'''#from load_data import data
#from recommender import algo

trainingSet = data.build_full_trainset()

algo.fit(trainingSet)
#Computing the cosine similarity matrix...
#Done computing similarity matrix.
#<surprise.prediction_algorithms.knns.KNNWithMeans object at 0x7f04fec56898>

prediction = algo.predict('B', 2)
prediction.est'''

"#from load_data import data\n#from recommender import algo\n\ntrainingSet = data.build_full_trainset()\n\nalgo.fit(trainingSet)\n#Computing the cosine similarity matrix...\n#Done computing similarity matrix.\n#<surprise.prediction_algorithms.knns.KNNWithMeans object at 0x7f04fec56898>\n\nprediction = algo.predict('B', 2)\nprediction.est"

In [ ]:
#df_original.head()

## Colaborative filtering using KNN:

In [ ]:

cf_df=df_original.pivot_table(index='Sub-Category',columns='Order ID',values='Quantity').fillna(0)
cf_df.head()

Order ID      CA-2019-101007  CA-2019-102281  ...  US-2019-156867  US-2019-164147
Sub-Category                                  ...
Bags                     0.0             6.0  ...             0.0             5.0
Belts                    2.0             0.0  ...             6.0             0.0
Dresses                  0.0             0.0  ...             3.0             0.0
Flip flops               0.0             3.5  ...             0.0             0.0
Formals                  0.0             8.0  ...             0.0             2.0

[5 rows x 66 columns]

In [ ]:
from scipy.sparse import csr_matrix

movie_features_df_matrix = csr_matrix(cf_df.values)

from sklearn.neighbors import NearestNeighbors


model_knn = NearestNeighbors(metric = 'cosine', algorithm = 'brute')
model_knn.fit(cf_df)

NearestNeighbors(algorithm='brute', metric='cosine')

In [ ]:
import numpy as np
query_index = np.random.choice(cf_df.shape[0])
print(query_index)
distances, indices = model_knn.kneighbors(cf_df.iloc[query_index,:].values.reshape(1, -1), n_neighbors = 6)

9

In [ ]:
for i in range(0, len(distances.flatten())):
    if i == 0:
        print('Recommendations for {0}:\n'.format(cf_df.index[query_index]))
    else:
        print('{0}: {1}, with distance of {2}:'.format(i, cf_df.index[indices.flatten()[i]], distances.flatten()[i]))

Recommendations for Sneakers:

1: Sportswear, with distance of 0.4118983803294769:
2: Jackets, with distance of 0.6109123064965762:
3: Dresses, with distance of 0.6761653451892149:
4: Formals, with distance of 0.761715746609342:
5: Heels & Flats, with distance of 0.8623084139765943:

## SVD:

In [ ]:
'''
U, S, V = np.linalg.svd(cf_df)'''

'\nU, S, V = np.linalg.svd(cf_df)'

In [ ]:
'''
def top_cosine_similarity(data, movie_id, top_n=10):
    index = movie_id - 1 # Movie id starts from 1
    movie_row = data[index, :]
    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))
    similarity = np.dot(movie_row, data.T) / (magnitude[index] * magnitude)
    sort_indexes = np.argsort(-similarity)
    return sort_indexes[:top_n]

# Helper function to print top N similar movies
def print_similar_movies(movie_data, movie_id, top_indexes):
    print('Recommendations for {0}: \n'.format(
    movie_data[movie_data[movie_id]== movie_id].title.values[0]))
    for id in top_indexes + 1:
        print(movie_data[movie_data[movie_id] == id].title.values[0])'''

"\ndef top_cosine_similarity(data, movie_id, top_n=10):\n    index = movie_id - 1 # Movie id starts from 1\n    movie_row = data[index, :]\n    magnitude = np.sqrt(np.einsum('ij, ij -> i', data, data))\n    similarity = np.dot(movie_row, data.T) / (magnitude[index] * magnitude)\n    sort_indexes = np.argsort(-similarity)\n    return sort_indexes[:top_n]\n\n# Helper function to print top N similar movies\ndef print_similar_movies(movie_data, movie_id, top_indexes):\n    print('Recommendations for {0}: \n'.format(\n    movie_data[movie_data[movie_id]== movie_id].title.values[0]))\n    for id in top_indexes + 1:\n        print(movie_data[movie_data[movie_id] == id].title.values[0])"

In [ ]:
'''
k = 50
movie_id = 1 # Grab an id from movies.dat
top_n = 10

sliced = V.T[:, :k] # representative data
indexes = top_cosine_similarity(sliced, movie_id, top_n)
print_similar_movies(cf_df, movie_id, indexes)'''

'\nk = 50\nmovie_id = 1 # Grab an id from movies.dat\ntop_n = 10\n\nsliced = V.T[:, :k] # representative data\nindexes = top_cosine_similarity(sliced, movie_id, top_n)\nprint_similar_movies(cf_df, movie_id, indexes)'

In [ ]:
import sklearn
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics import accuracy_score


SVD = TruncatedSVD(n_components=12, random_state=17)
result_matrix = SVD.fit_transform(cf_df.values.T)
result_matrix.shape

(66, 12)

In [ ]:
# PearsonR coef 
corr_matrix = np.corrcoef(result_matrix)
corr_matrix.shape
cf_df.values.T

array([[0., 2., 0., ..., 0., 0., 0.],
       [6., 0., 0., ..., 0., 0., 0.],
       [7., 0., 4., ..., 0., 9., 6.],
       ...,
       [0., 0., 7., ..., 0., 0., 0.],
       [0., 6., 3., ..., 0., 0., 0.],
       [5., 0., 0., ..., 0., 0., 0.]])

In [ ]:
#https://www.kaggle.com/zolboo/recommender-systems-knn-svd-nn-keras
cf_df2=df_original.pivot_table(index='Order ID',columns='Sub-Category',values='Quantity').fillna(0)
cf_df.head()

Order ID      CA-2019-101007  CA-2019-102281  ...  US-2019-156867  US-2019-164147
Sub-Category                                  ...
Bags                     0.0             6.0  ...             0.0             5.0
Belts                    2.0             0.0  ...             6.0             0.0
Dresses                  0.0             0.0  ...             3.0             0.0
Flip flops               0.0             3.5  ...             0.0             0.0
Formals                  0.0             8.0  ...             0.0             2.0

[5 rows x 66 columns]

In [ ]:
# get the index of the popular restaurant
restaurant_names = cf_df.columns
restaurants_list = list(restaurant_names)

popular_rest = restaurants_list.index('CA-2019-103730')
print("index of the popular restaurant: ", popular_rest)

index of the popular restaurant:  2

In [ ]:
# restaurant of interest 
corr_popular_rest = corr_matrix[popular_rest]
corr_popular_rest.shape

(66,)

In [ ]:
list(restaurant_names[(corr_popular_rest < 1.0) & (corr_popular_rest > 0.9)])

['CA-2019-103730']

In [ ]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim = linear_kernel(cf_df, cf_df)

In [ ]:
cosine_sim[0]

array([284.25      ,  23.        ,  71.        ,  36.        ,
        68.        ,  10.        ,  48.5       ,  25.        ,
        63.        ,  28.33333333,  20.        ,  83.        ,
         0.        ,  51.        ,  63.        ,  74.        ])

In [ ]:
#smd = smd.reset_index()
titles = df_original['Sub-Category']
indices = pd.Series(df.index, index=df_original['Sub-Category'])

In [ ]:
#https://www.kaggle.com/zolboo/recommender-systems-knn-svd-nn-keras
# the most POPULAR restaurants by stars.
df_original.groupby('Sub-Category')['Quantity'].count().sort_values(ascending=False).head()

Sub-Category
Formals     20
Bags        16
Dresses     15
Jackets     14
Sneakers    13
Name: Quantity, dtype: int64

In [ ]:
# see the NAME of the most popular restaurant
Filter = df_original['Sub-Category'] == 'Formals'
#print("Name: ", df_original[Filter]['name'].unique())
#print("Address:", df_original[Filter]['address'].unique())

In [ ]:
#https://www.kaggle.com/cast42/simple-svd-movie-recommender

user_item = df_original.groupby(['Sub-Category', 'Order ID'])['Quantity'].first().unstack(fill_value=0.0)

from scipy.sparse.linalg import svds
U, sigma, Vt = svds(user_item, k = 15)

In [ ]:
sigma_diag_matrix=np.diag(sigma)

In [ ]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma_diag_matrix), Vt)
#all_user_predicted_ratings_demeaned = all_user_predicted_ratings +  user_ratings_mean.reshape(-1, 1)
preds_df = pd.DataFrame(all_user_predicted_ratings, columns = user_item.columns, index=user_item.index)

In [ ]:
preds_df.head()

Order ID      CA-2019-101007  CA-2019-102281  ...  US-2019-156867  US-2019-164147
Sub-Category                                  ...
Bags               -0.003728        6.172257  ...        0.031228        4.961650
Belts               1.999318        0.031495  ...        6.005710       -0.007012
Dresses             0.001072       -0.049550  ...        2.991017        0.011031
Flip flops          0.031895        2.526113  ...       -0.267197        0.328133
Formals            -0.004508        8.208322  ...        0.037766        1.953621

[5 rows x 66 columns]

In [ ]:
movies_user_42 = user_item
high_rated_movies_42 = movies_user_42[movies_user_42 > 3].index
high_rated_movies_42

Index(['Bags', 'Belts', 'Dresses', 'Flip flops', 'Formals', 'Heels & Flats',
       'Jackets', 'Jeans', 'Nightwear', 'Sneakers', 'Socks', 'Sport shoes',
       'Sportswear', 'Sunglasses', 'T-shirts ', 'Tops'],
      dtype='object', name='Sub-Category')

In [ ]:
def get_high_recommended_movies(userId):
    movies_rated_by_user = user_item.loc[userId]
    movies_high_rated_by_user =  movies_rated_by_user[movies_rated_by_user > 3].index
    movies_recommended_for_user = preds_df.loc[userId]
    movies_high_recommend_for_user = movies_recommended_for_user[movies_recommended_for_user > 3].index
    return set(movies_high_recommend_for_user) - set(movies_high_rated_by_user)

In [ ]:
#get_high_recommended_movies('CA-2019-101007')

## FP GROWTH

In [ ]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(df1).transform(df1)
df_fp = pd.DataFrame(te_ary, columns=te.columns_)
df_fp

               D      I      O      a      d      e      l      r      u      v
0    True   True   True   True  False   True   True  False   True  False  False
1   False  False  False  False   True  False   True   True  False   True   True
2   False  False  False  False  False  False  False  False  False  False  False
3   False  False  False  False  False  False  False  False  False  False  False
4   False  False  False  False  False  False  False  False  False  False  False
..    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...
61  False  False  False  False  False  False  False  False  False  False  False
62  False  False  False  False  False  False  False  False  False  False  False
63  False  False  False  False  False  False  False  False  False  False  False
64  False  False  False  False  False  False  False  False  False  False  False
65  False  False  False  False  False  False  False  False  False  False  False

[66 rows x 11 columns]

In [ ]:
#!pip install mlxtend
#!pip install apyori
#!pip install pyfpgrowth

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#!pip install mlxtend
#!pip install apyori
from apyori import apriori 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import fpgrowth
from mlxtend.preprocessing import TransactionEncoder

import pyfpgrowth

##FACING ISSUES IN FP GROWTH IN COLAB HOWEVER THIS IS WORKING IN JUPYTER 
"""fre_itemsets=FPGrowth(df_fp,min_support=0.09,use_colnames=True)
fre_itemsets"""

'fre_itemsets=FPGrowth(df_fp,min_support=0.09,use_colnames=True)\nfre_itemsets'

In [ ]:
from mlxtend.frequent_patterns import fpgrowth

#fpgrowth(df, min_support=0.5, use_colnames=True)

In [ ]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(list_ca).transform(list_ca)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

     Bags  Belts  Dresses  Flip flops  ...  Sportswear  Sunglasses  T-shirts    Tops
0   False   True    False       False  ...       False       False      False  False
1    True  False    False        True  ...       False       False      False  False
2    True  False     True       False  ...       False       False       True   True
3   False  False    False       False  ...       False       False      False  False
4   False  False     True       False  ...       False       False      False  False
..    ...    ...      ...         ...  ...         ...         ...        ...    ...
61  False  False    False       False  ...       False       False      False  False
62  False  False    False       False  ...       False       False      False  False
63  False  False     True       False  ...       False       False      False  False
64  False   True     True       False  ...       False       False      False  False
65   True  False    False       False  ...       False       False      False  False

[66 rows x 16 columns]

In [ ]:
!pip install mlxtend --upgrade --no-deps
!pip install --no-binary :all: mlxtend


from mlxtend.frequent_patterns import fpgrowth

#fpgrowth(df, min_support=0.6)

Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.19.0)
Requirement already satisfied: mlxtend in /usr/local/lib/python3.7/dist-packages (0.19.0)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.3.5)
Requirement already satisfied: setuptools in /usr/local/lib/python3.7/dist-packages (from mlxtend) (57.4.0)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.4.1)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (3.2.2)
Requirement already satisfied: scikit-learn>=0.20.3 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.0.2)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.1.0)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.7/dist-packages (from mlxtend) (1.19.5)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.3.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.0.7)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.2->mlxtend) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.1->matplotlib>=3.0.0->mlxtend) (1.15.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn>=0.20.3->mlxtend) (3.1.0)

## DEEP LEARNING

In [ ]:
import numpy as np
import pandas as pd
import os
import warnings

In [ ]:
from keras.models import load_model
from sklearn.model_selection import train_test_split
from keras.layers import Input, Embedding, Flatten, Dot, Dense, Concatenate
from keras.models import Model
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
df_new={
    'user_id': [196,186,22,244,166,22,123,321],
    'item_id':[242,302,377,51,246,11,233,11],
    'rating':[3,3,1,2,1,2,3,1],
    'timespan':[3,1,1,11,0,9,6,11]
}
df_new=pd.DataFrame.from_dict(df_new)
df_new.head()

   user_id  item_id  rating  timespan
0      196      242       3         3
1      186      302       3         1
2       22      377       1         1
3      244       51       2        11
4      166      246       1         0

In [ ]:
#train, test = train_test_split(df_original.iloc[:,[0,10,12]], test_size=0.2, random_state=42)
x_train, x_test, y_train, y_test = train_test_split(df_new[['user_id','item_id']],df_new[['rating']], test_size=0.2, random_state=2)
#train.rating
x_train['user_id']

6    123
2     22
3    244
7    321
5     22
0    196
Name: user_id, dtype: int64

In [ ]:
# creating book embedding path
movie_input = Input(shape=[1], name="Movie-Input")
n_items=5
n_users=5
movie_embedding = Embedding(n_items+1, 5, name="Movie-Embedding")(movie_input)
movie_vec = Flatten(name="Flatten-Books")(movie_embedding)
# creating user embedding path
user_input = Input(shape=[1], name="User-Input")
user_embedding = Embedding(n_users+1, 5, name="User-Embedding")(user_input)
user_vec = Flatten(name="Flatten-Users")(user_embedding)
# concatenate features
conc = Concatenate()([movie_vec, user_vec])
# add fully-connected-layers
fc1 = Dense(128, activation='relu')(conc)
fc2 = Dense(32, activation='relu')(fc1)
out = Dense(1)(fc2)
# Create model and compile it
model2 = Model([user_input, movie_input], out)
model2.compile('adam', 'mean_squared_error')

In [ ]:
#history = model2.fit([x_train['user_id'], x_train['user_id']], y_train, epochs=2, verbose=1)

In [ ]:
predictions = model2.predict([192, 242])
[print(predictions[i], test.rating.iloc[i]) for i in range(0,1)]